// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/countries": {
            "get": {
                "description": "Sort countries by GDP, area, population, inflation, global rank, or LATAM rank.",
                "produces": [
                    "application/json"
                ],
                "summary": "Sort countries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sorting parameter",
                        "name": "sort_by",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.Country"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.Country": {
            "type": "object",
            "properties": {
                "area_sq_km": {
                    "type": "integer"
                },
                "border_length_km": {
                    "type": "integer"
                },
                "borders": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "flag_url": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            }
                        }
                    }
                },
                "capital": {
                    "type": "string"
                },
                "climates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "currencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "current_leader": {
                    "type": "string"
                },
                "economic_strengths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "flag_url": {
                    "type": "string"
                },
                "gdp_per_capita": {
                    "type": "integer"
                },
                "global_rank": {
                    "type": "integer"
                },
                "government_system": {
                    "type": "string"
                },
                "inflation_rate": {
                    "type": "number"
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "latam_rank": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "population": {
                    "type": "integer"
                },
                "total_gdp": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "LATAM Info API",
	Description:      "This API provides country information and allows sorting by various parameters.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
